DATA = {
"Mia" : "crushiee cakes ko po",
"Engr. Sean" : "pogi na teacher namin sa comprog",
"Glenn Domo" : "pogi na student ni Engr. Gab",
"Engineering Drawing" : "hindi po ako magaling mag drawing",
"Calculus" : "mamatay nalang",
"Derivatives" : "a derivative is the rate of a function at a specific point",
"Anti Derivative" : "primative integral or indefinite integral",
"Derivative of 10" : "0",
"Derivative of 10x" : "10",
"Derivative of 10x raised to 2": "20x",
"Sin x" : "cos x",
"Cos x" : "-sin x",
"Tan x" : "sec squared x",
"Sec x" : "sec x tan x",
"Cot X" : "-csc squared x",
"Analog Computer" : "Used to process data",
"Digital Computer" : "Electronic devices",
"4th Gen Computer" : "Invented in year 1971-1980",
"3rd Gen Computer" : "Has integrated circuits",
"2nd Gen Computer" : "Invented in 1957-1963",
"1st Gen Computer" : "Invented in 1940-1956",
"Mark 1" : "Invented in 1944 by Howard Aiken",
"Differential Analyzer" : "Introduce in 1930",
"Tablulating Machine" : "Invented by Hermann Hollerith",
"Analytical Engine": "Invented by Charles Babbage",
"Leibniz Wheel" : "Invented by Willhelm Leibniz",
"Pascaline" : "Invented by Blaise Pascal",
"Napiers Bone" : "Invented by John Napier",
"Abacus" : "The first computer",
}
a = input("SEARCH.")
print(DATA[a])
    